# Generated by Django 4.2 on 2024-08-29 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sumary', models.CharField(blank=True, max_length=250)),
                ('content', models.TextField()),
                ('date_pub', models.DateField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.categories')),
            ],
        ),
    ]
