# Generated by Django 4.2 on 2024-08-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_content_alter_articles_date_pub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='publiche',
            field=models.BooleanField(default=False, verbose_name='publier'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=100, verbose_name='titre'),
        ),
    ]
