# Generated by Django 4.2 on 2024-08-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_publiche_alter_categories_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='imagearticle',
            field=models.ImageField(null=True, upload_to='article_image'),
        ),
    ]
