[pytest]
DJANGO_SETTINGS_MODULE = blogs.settings
# -- recommended but optional:
python_files = tests.py test_*.py *_tests.py tests_* *_test_.py
[tool:pystes]
addopts = --cov=blogs --cov-report term-missing
