name: pipeline ci/cd build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check_syntaxe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Utilisation de l'action checkout pour récupérer le code

      - name: Set up Python
        uses: actions/setup-python@v2  # Utilisation de l'action setup-python pour configurer Python
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt  # Exécution de la commande pour installer les dépendances

      - name: Check code syntax
        run: |
          flake8 . --exit-zero  # Exécution de flake8 pour vérifier la syntaxe du code
